// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

using UnityEngine;

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1200 // Using directives should be placed correctly
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace MessagePack.Formatters.Shared.Move
{
    using System;
    using System.Buffers;
    using MessagePack;

    public sealed class MoveEventFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Shared.Move.MoveEvent>
    {


        public void Serialize(ref MessagePackWriter writer, global::Shared.Move.MoveEvent value, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (value == null)
            {
                writer.WriteNil();
                return;
            }

            IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(7);
            writer.Write(value.PlayerId);
            writer.Write(value.RoomId);
            writer.Write(value.Distance);
            writer.Write(value.Angle);
            formatterResolver.GetFormatterWithVerify<Quaternion>().Serialize(ref writer, value.Rotation, options);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.Direction, options);
            formatterResolver.GetFormatterWithVerify<Vector3>().Serialize(ref writer, value.Position, options);
        }

        public global::Shared.Move.MoveEvent Deserialize(ref MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                return null;
            }

            options.Security.DepthStep(ref reader);
            IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __PlayerId__ = default(byte);
            var __RoomId__ = default(byte);
            var __Distance__ = default(float);
            var __Angle__ = default(float);
            var __Rotation__ = default(Quaternion);
            var __Direction__ = default(Vector3);
            var __Position__ = default(Vector3);

            for (int i = 0; i < length; i++)
            {
                var key = i;

                switch (key)
                {
                    case 0:
                        __PlayerId__ = reader.ReadByte();
                        break;
                    case 1:
                        __RoomId__ = reader.ReadByte();
                        break;
                    case 2:
                        __Distance__ = reader.ReadSingle();
                        break;
                    case 3:
                        __Angle__ = reader.ReadSingle();
                        break;
                    case 4:
                        __Rotation__ = formatterResolver.GetFormatterWithVerify<Quaternion>().Deserialize(ref reader, options);
                        break;
                    case 5:
                        __Direction__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    case 6:
                        __Position__ = formatterResolver.GetFormatterWithVerify<Vector3>().Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Shared.Move.MoveEvent();
            ____result.PlayerId = __PlayerId__;
            ____result.RoomId = __RoomId__;
            ____result.Distance = __Distance__;
            ____result.Angle = __Angle__;
            ____result.Rotation = __Rotation__;
            ____result.Direction = __Direction__;
            ____result.Position = __Position__;
            reader.Depth--;
            return ____result;
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1200 // Using directives should be placed correctly
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
